
import React from 'react';
import { Nav } from '../../components/Nav';
import  Head from 'next/head';
import { useRouter } from 'next/router';



export default function Products(){
    const { category } = useRouter().query
    return <div>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Nav/>
    <div>
        <h6>This is products page, with category = {category}</h6>
    </div>
  </div>
}