
import React, { useState } from 'react';
import { Nav } from '../../components/Nav';
import Head from 'next/head';
import { useRouter } from 'next/router';
import ProductCard from '../../components/ProductCard';
import { Divider, Grid, Input, Loading, Select, Spacer, Spinner, Text, useMediaQuery, useTheme } from '@geist-ui/react';
import { useProducts } from '../../frameworks/supabase/swr/products';
import { useCategories } from '../../frameworks/supabase/swr/categories';



export default function Products() {
  const { category } = useRouter().query
  const { data: cateogries } = useCategories()

  const [filter, setFilter] = useState({
    category: '',
    label: ''
  })

  const { data: products, isLoading } = useProducts(filter)

  const theme = useTheme()
  const isMobile = useMediaQuery('mobile')
  return <div style={{ background: theme.palette.accents_1, minHeight: '100vh' }} >
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Nav />
    <div style={{ background: "#fff" }} >
      <Select onChange={(val) => {
        setFilter({ ...filter, category: val })
      }} scale={1.2} height={'60px'} style={{ borderWidth: 0, }} placeholder="Select category" >
        {cateogries?.map((item, id) => <Select.Option key={id} value={`${item.id}`}>{item.label}</Select.Option>)}
        <Select.Option value={``}>All</Select.Option>
      </Select>

      <input
        onKeyDown={(e) => {
          if (e.key == 'Enter') {
            setFilter({ ...filter, label: e.target.value })
          }
        }} onBlur={(e) => setFilter({ ...filter, label: e.target.value })}
        placeholder='search for products' type="text" />
    </div>
    <Spacer />
      {isLoading && <Loading spaceRatio={2} scale={2}></Loading>}
    <Grid.Container direction='row' gap={isMobile ? 0 : 2}  >
      {
        products?.map((item, id) => <Grid justify='center' alignItems='center' key={id} xs={24} sm={12} md={6} >
          <ProductCard width={300} height={300} data={item} />
        </Grid>)
      }
    </Grid.Container>
    <style jsx>{
      `
        input {
          border: none;
        }
      `
    }

    </style>

  </div>
}
