import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { supabase } from '../frameworks/supabase'
import { Nav } from '../components/Nav'
import { Text } from '@geist-ui/react'
import { Carousel} from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import { width } from 'dom-helpers'
export default function Home({user}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div style = {{
        display: 'flex',
        flexDirection: 'column'
      }}>

        <Carousel style = {{
          height: '600px',
          margin: '1% 0%'
        }}>
          <Carousel.Item>
            <img style = {{
              height: '600px',
              width: '100%',
              boxShadow: '0px 0px 10px 10px grey inset'
            }}
              className="d-block w-100"
              src="https://static-buyma-jp.akamaized.net/imgdata/item/210629/0070803294/368058123/428.jpg"
              alt="First slide"
            />
            <Carousel.Caption style = {{
              color: 'black'
            }}>
              <h3>Something</h3>
              <p>PR for this product</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img style = {{
              height: '600px',
              width: '100%',
              boxShadow: '0px 0px 10px 10px grey inset'
            }}
              className="d-block w-100"
              src="https://static-buyma-jp.akamaized.net/imgdata/item/210629/0070803294/368058123/428.jpg"
              alt="Second slide"
            />

            <Carousel.Caption style = {{
              color: 'black'
            }}>
              <h3>Second slide label</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </Carousel.Caption>
          </Carousel.Item>
          <Carousel.Item>
            <img style = {{
              height: '600px',
              width: '100%',
              boxShadow: '0px 0px 10px 10px grey inset'
            }}
              className="d-block w-100"
              src="https://static-buyma-jp.akamaized.net/imgdata/item/210629/0070803294/368058123/428.jpg"
              alt="Third slide"
            />

            <Carousel.Caption style = {{
              color: 'black'
            }}>
              <h3>Third slide label</h3>
              <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </Carousel.Caption>
          </Carousel.Item>
        </Carousel>
        <div style = {{
          display: 'flex',
          flexDirection: 'row'
        }}>
          <div style = {{
            display: 'grid',

          }}>

          </div>
          <div style = {{
            
          }}>
            <img src = ""></img>
          </div>
        </div>
      </div>
    </div>
  )
}



export async function getServerSideProps({ req }) {
  const { user } = await supabase.auth.api.getUserByCookie(req)

  // If there is a user, return it.
  return { props: { user } }
}